" Dont overwrite settings
if exists('skip_defaults_vim')
  finish
endif

set viminfo+=n~/.vim/viminfo
set history=100
set wildmenu

" Enable mouse support
if has('mouse')
  set mouse=a
endif

" Disable visual and audio bell
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Set UTF-8
set encoding=utf-8
set fileencoding=utf-8

source $XDG_CONFIG_HOME/vim/common.vim
