" Dont overwrite settings
if exists('skip_defaults_vim')
  finish
endif

set viminfo+=n~/.vim/viminfo
set history=100
set wildmenu

" Enable mouse support
if has('mouse')
  set mouse=a
endif

" Disable visual and audio bell
set noerrorbells visualbell t_vb=
autocmd GUIEnter * set visualbell t_vb=

" Set UTF-8
set encoding=utf-8
set fileencoding=utf-8

" Remember last cursor position
autocmd BufReadPost *
  \ if line("'\"") >= 1 && line("'\"") <= line("$") && &ft !~# 'commit'
  \ |   exe "normal! g`\""
  \ | endif

" Convert tab to spaces
set expandtab
set shiftwidth=4
set softtabstop=4

" Automatic indentation
set nocindent
set autoindent
set smartindent

" Sets line numbers relative to the current line
set number
set relativenumber

" Set minimal distance from cursor to border
set scrolloff=8

" Enable Highlighting
if &t_Co >= 8 || has("gui_running")
  syntax on
  set hlsearch
endif

" Set colorscheme
if &t_Co >= 256 || has("gui_running")
  colorscheme wombat256jumper
else
  colorscheme default
endif

" Configure vim-airline
let g:airline#extensions#tabline#enabled=1
if &t_Co >= 256 || has("gui_running")
  let g:airline_theme='wombat'
else
  let g:airline_symbols_ascii=1
endif

" Highlight current line
augroup CursorLine
  autocmd!
  autocmd VimEnter,WinEnter,BufWinEnter * setlocal cursorline
  autocmd WinLeave * setlocal nocursorline
augroup END

" Makes information not be shown 2 times with vim-airline
set shortmess=F

" Enable file type detection
filetype plugin indent on

" Provides X-clipboard support (requires gvim)
vmap <C-c> "+yi<ESC>
vmap <C-x> "+c<ESC>
vmap <C-v> c<ESC>"+p
imap <C-v> <C-r><C-o>+

" Removes Highlighting from search patterns
nnoremap <silent> <Space> :nohlsearch<Enter>

" vim-latexsuite
let g:tex_flavor="latex"
let g:tex_no_error=1      " Dont highlight underscores (_)
let g:Tex_SmartKeyQuote=0 " Dont change quotation marks to special upper and lower

" Commands
command W :execute ':silent w !sudo tee % > /dev/null' | :edit!
command Wq :execute ':silent w !sudo tee % > /dev/null' | :quit!

" Hotkeys
nmap mm :w <Enter>:!./% <Enter>
nmap mt :w <Enter>:!pdflatex -interaction nonstopmode -halt-on-error -file-line-error % <Enter>
