#!/usr/bin/env bash

# input cannot contain '\n'

function inTerminal() {
    OLD_PS3="$PS3"
    PS3=" $(tput setaf 11)$(tput bold)>$(tput sgr0) "

    select decision in "$@"
    do
        echo "$decision"
        break
    done

    PS3="$OLD_PS3"
}

LIST=""
for arg in "$@" # put everything in a list
do
    LIST="$LIST$arg\n"
done

if [ ${#LIST} -gt 0 ] # cut off last '\n'
then
    LIST=${LIST:0:$((${#LIST} - 2))}
fi

if [ -n "$DISPLAY" ]
then
    RETURNSTRING="$(echo -e "$LIST" | rofi -dmenu)"
else
    SPACEDLIST=$(echo "$LIST" | sed 's/\\n/ /g')
    RETURNSTRING="$(inTerminal $SPACEDLIST)"
fi

if [ -n "$RETURNSTRING" ]
then
    echo "$RETURNSTRING"
else
    exit 1
fi
