#!/usr/bin/env bash

# depends: glava (3cc5e226aa719328f1b96870617a0e9a95f02c8a), xrandr

FOREGROUND="#85678f"
BACKGROUND="#373b41"

# in pixel (eg. "100") or percent (eg. "10%")
WIDTH="$(( (128 * 2) + (150 * 2) ))"
HEIGHT="${WIDTH}"

MONITORS="$(xrandr --listactivemonitors)"
MONITOR="$(echo "${MONITORS}" | grep --extended-regexp '^\s+[0-9]+:\s+\+\*')"
RESOLUTION="$(echo "${MONITOR}" | cut --fields=4 --delimiter=' ' \
    | cut --fields=1 --delimiter='+' | sed 's/x/\n/g' \
    | cut --fields=1 --delimiter='/' | tr '\n' ' ')"
XRES=$(echo "${RESOLUTION}" | cut --fields=1 --delimiter=' ' \
    | grep --extended-regexp '^[0-9]+$')
YRES=$(echo "${RESOLUTION}" | cut --fields=2 --delimiter=' ' \
    | grep --extended-regexp '^[0-9]+$')

if [[ -z "${XRES}" ]] || [[ -z "${YRES}" ]]; then
    echo "can't access screen resolution"
    exit 1
fi

function percentage_to_pixel {
    local res="${1}"
    local prcnt="$(echo "${2}" | grep --extended-regexp '^[0-9]+%$' \
        | tr --delete '%')"
    if [[ -z "${prcnt}" ]]
    then
        echo "${2}"
    else
        echo "$(( (res * prcnt) / 100 ))"
    fi
}

WIDTH="$(percentage_to_pixel "${XRES}" "${WIDTH}")"
HEIGHT="$(percentage_to_pixel "${YRES}" "${HEIGHT}")"

# 30 pixel padding bottom_right hardcoded
XPAD="$(( XRES - (WIDTH + 30) ))"
YPAD="$(( YRES - (HEIGHT + 30) ))"

XFULL="$((XPAD + WIDTH))"
YFULL="$((YPAD + HEIGHT))"

if [[ "${XRES}" -lt "${XFULL}" ]] || \
    [[ "${YRES}" -lt "${YFULL}" ]]; then
    echo "screen resolution is only ${XRES}x${YRES} but is required to be at least ${XFULL}x${YFULL}"
    exit 2
fi

echo "fg = ${FOREGROUND}; bg = ${BACKGROUND}" \
    | sed 's/;\s*/\n/g' \
    | glava --desktop --verbose \
        --pipe="fg" \
        --pipe="bg" \
        --request="mod radial" \
        --request="setopacity \"xroot\"" \
        --request="setgeometry ${XPAD} ${YPAD} ${WIDTH} ${HEIGHT}" \
        --request="setxwintype \"!-\""
