#!/usr/bin/env bash

MOUNTPATH="${HOME}/Storage"
DOMAIN="nix200.wireguard"

case "${1}" in
    'mount')
        echo "mounting Storage at: ${MOUNTPATH}"
        sshfs "jumper@${DOMAIN}:Storage" "${MOUNTPATH}"
        ;;

    'umount')
        echo "unmounting Storage from: ${MOUNTPATH}"
        fusermount3 -u "${MOUNTPATH}"
        ;;

    *)
        exit 1
        ;;
esac
