#!/usr/bin/env sh

# depends: rsync, ssh

# TODO: init automatically
# sudo -u mpd mkdir -p /var/lib/mpd/music/Storage
# sudo -u mpd chmod g+w /var/lib/mpd/music/Storage

# TODO: somehow this needs to be run twice to sync all directories (also those with spaces in the name)
# paths, users and hosts are hardcoded here!
rsync --archive --verbose --chown=jumper:mpd --chmod="D0755,F644" jumper@nix200.wireguard:~/Storage/Music /var/lib/mpd/music/Storage
