#!/usr/bin/env bash

source ~/.system-info.sh
DEVICE="$MAIN_TOUCHPAD"

case "${1}" in
    'init')
        xinput set-prop "$DEVICE" "libinput Tapping Enabled" 1
        xinput set-prop "$DEVICE" "libinput Natural Scrolling Enabled" 1
        xinput set-prop "$DEVICE" "Device Enabled" 0
        ;;

    'toggle')
        STRING=$(xinput list-props "$DEVICE" | grep "Device Enabled")
        STATE=${STRING:$(expr ${#STRING} - 1):1}

        NEWSTATE=$(( $(($STATE + 1)) % 2))

        xdotool mousemove 0 0
        xinput set-prop "$DEVICE" "Device Enabled" $NEWSTATE
        ;;

    *)
        exit 1
        ;;
esac
